title: "Custodial Account Guide (U.S. → Abroad)"
description: "A complete guide for immigrant parents managing U.S. custodial accounts with future plans to manage them from abroad."
remote_theme: just-the-docs/just-the-docs

# Theme features
logo: "/asset/logo.png"
search_enabled: true
color_scheme: dark
aux_links:
  "GitHub Repo": "https://github.com/kamalsoft/USA-Custodial-Account-Guide"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-remote-theme

# Enable Mermaid
mermaid:
  version: "10.2.4"

# Navigation
collections:
  docs:
    output: true
    permalink: /docs/:name

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: default